---
- hosts: osd1 osd2 osd3
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
 
  - name: Install NTP
    apt:
      name: ntp
      state: present
  - name: Install Ceph-deploy
    apt:
      name: ceph-deploy
      state: present
  - name: Install Ansible
    apt:
      name: ansible
      state: present
 # ansible should be installed only in 1 machine, but for tests I'll install to all nodes
 # - name: Insert configurations
  - script: ./configs.sh 
