---
- hosts: mon1 mon2 mon3 osd1 osd2 osd3
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
 
  - name: Install NTP
    apt:
      name: ntp
      state: present
  - name: Install Ceph-deploy
    apt:
      name: ceph-deploy
      state: present
#  - name: Insall SSHPASS
#    apt:
#      name: sshpass
#      state: present
#  - name : Making Directory
#    file:
#      path: "/etc/ceph"
#      state: directory